version: '3'

services:
   db:
     image: mysql:5.7.20
     volumes:
       - db_data:/var/lib/docker/mysql
     restart: always
     ports:
        - 3307:3306
     environment:
       MYSQL_ROOT_PASSWORD: P@sswordsRC00l
       MYSQL_DATABASE: threatkb
       MYSQL_USER: threatkb
       MYSQL_PASSWORD: P@sswordsRC00l
   redis:
     depends_on:
       - db
     image: redis:latest
     ports:
       - 6379:6379
     restart: always
   threatkb:
     depends_on:
       - db
     image: threatkb:latest
     ports:
       - 5000:5000
     restart: always
     environment:
       THREATKB_USER: admin@inquest.net
       THREATKB_PASS: P@sswordsRC00l
       MYSQL_ROOT_PASSWORD: P@sswordsRC00l
       SQL_DATABASE: threatkb
       SQL_USERNAME: threatkb
       SQL_PASSWORD: P@sswordsRC00l
       SQL_PORT: 3306
       SQL_HOST: db
       SQL_PROTOCOL: mysql
       LISTEN_ON: 0.0.0.0
       LISTEN_PORT: 5000
   threatkb_agent:
     depends_on:
       - db
     image: threatkb:latest
     restart: always
     environment:
       - RUN_AGENT=1
       - C_FORCE_ROOT=1
volumes:
    db_data:
